---
abstract: 'Connect to the Capsule API (www.capsulecrm.com)'
author:
  - 'Simon Elliott <cpan@papercreatures.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300001, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-CapsuleCRM
requires:
  HTTP::Request::Common: 0
  JSON::XS: 0
  Method::Signatures: 0
  Moo: 0
  Sub::Quote: 0
  XML::Simple: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Net-CapsuleCRM
  homepage: https://github.com/purge/Net-CapsuleCRM/wiki
  repository: git://github.com/purge/Net-CapsuleCRM.git
version: 1.112630
